# Generated by Django 2.2.14 on 2021-08-12 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210812_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postee',
            new_name='Post',
        ),
    ]
